name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0   # FTPを使ってサーバーにDeployするアクションを実行
      env:                                        # FTP環境の設定を行う
        FTP_SERVER: ${{ secrets.FTP_SERVER }}     # FTPサーバーのURLを設定
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }} # FTPのユーザー名を設定
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }} # FTPのパスワードを設定
        REMOTE_DIR: /home/rwzyscpo/public_html/resume-cloud.work # リモートのどのディレクトリにアップロードするか
        ARGS: --delete
        # --delete arg will delete files on the server if you've deleted them in git
